export const THEME_LIST = [
  {
    id: "t1",
    name: "Modern White",
    previewBg: "bg-white",
    previewItem: "bg-gray-200",
    cfg: {
      textColor: "#1f2937",
      btnBgColor: "#f3f4f6",
      btnTextColor: "#1f2937",
      btnBorderColor: "transparent",
      btnRounded: "pill",
      btnStyle: "none",
      bgGradient: "linear-gradient(135deg, #e0e7ff 0%, #fdf2f8 100%)",
      bgImage: "",
    },
  },
  {
    id: "t2",
    name: "Midnight Dark",
    previewBg: "bg-slate-900",
    previewItem: "bg-slate-600",
    cfg: {
      textColor: "#f8fafc",
      btnBgColor: "#1e293b",
      btnTextColor: "#f8fafc",
      btnBorderColor: "#334155",
      btnRounded: "rounded",
      btnStyle: "outline",
      bgGradient: "linear-gradient(135deg, #0f172a 0%, #1e1b4b 100%)",
      bgImage: "",
    },
  },
  {
    id: "t3",
    name: "Sweet Pastel",
    previewBg: "bg-purple-100",
    previewItem: "bg-purple-300",
    cfg: {
      textColor: "#4c1d95",
      btnBgColor: "#ffffff",
      btnTextColor: "#7c3aed",
      btnBorderColor: "#ddd6fe",
      btnRounded: "pill",
      btnStyle: "shadow3d",
      bgGradient: "linear-gradient(135deg, #fce7f3 0%, #ede9fe 100%)",
      bgImage: "",
    },
  },
  {
    id: "t4",
    name: "Forest Green",
    previewBg: "bg-green-50",
    previewItem: "bg-green-400",
    cfg: {
      textColor: "#14532d",
      btnBgColor: "#22c55e",
      btnTextColor: "#ffffff",
      btnBorderColor: "transparent",
      btnRounded: "square",
      btnStyle: "none",
      bgGradient: "linear-gradient(135deg, #ecfdf5 0%, #d1fae5 100%)",
      bgImage: "",
    },
  },
  {
    id: "t5",
    name: "Sunset Orange",
    previewBg: "bg-orange-50",
    previewItem: "bg-orange-400",
    cfg: {
      textColor: "#7c2d12",
      btnBgColor: "#f97316",
      btnTextColor: "#ffffff",
      btnBorderColor: "transparent",
      btnRounded: "pill",
      btnStyle: "none",
      bgGradient: "linear-gradient(135deg, #fff7ed 0%, #ffedd5 100%)",
      bgImage: "",
    },
  },
  {
    id: "t6",
    name: "Ocean Blue",
    previewBg: "bg-blue-50",
    previewItem: "bg-blue-500",
    cfg: {
      textColor: "#1e3a5f",
      btnBgColor: "#3b82f6",
      btnTextColor: "#ffffff",
      btnBorderColor: "transparent",
      btnRounded: "rounded",
      btnStyle: "shadow3d",
      bgGradient: "linear-gradient(135deg, #eff6ff 0%, #dbeafe 100%)",
      bgImage: "",
    },
  },
  {
    id: "t7",
    name: "Rose Gold",
    previewBg: "bg-pink-50",
    previewItem: "bg-pink-400",
    cfg: {
      textColor: "#881337",
      btnBgColor: "#ffffff",
      btnTextColor: "#f43f5e",
      btnBorderColor: "#fecdd3",
      btnRounded: "pill",
      btnStyle: "outline",
      bgGradient: "linear-gradient(135deg, #fff1f2 0%, #fce7f3 100%)",
      bgImage: "",
    },
  },
  {
    id: "t8",
    name: "Neon Dark",
    previewBg: "bg-gray-950",
    previewItem: "bg-cyan-400",
    cfg: {
      textColor: "#e2e8f0",
      btnBgColor: "#0f172a",
      btnTextColor: "#22d3ee",
      btnBorderColor: "#22d3ee",
      btnRounded: "square",
      btnStyle: "outline",
      bgGradient: "linear-gradient(135deg, #020617 0%, #0c1445 100%)",
      bgImage: "",
    },
  },
];